name: curviriver-dev
channels:
- conda-forge
- nodefaults
dependencies:
- python>=3.11

- numpy >=1.21
- pandas >=1
- geopandas-base >=0.12
- pyproj >=2.2
- scikit-learn >=1.3
- scipy
- shapely >=2.0
# optional
- joblib

# dev deps
- ipywidgets
- ipykernel
- matplotlib-base
- mapclassify
- folium
- pyogrio
- py3dep
- pygeohydro
- pyflwdir

- pip
- pip:
  - git+https://github.com/hyriver/async-retriever.git
  - git+https://github.com/hyriver/hydrosignatures.git
  - git+https://github.com/hyriver/pygeoogc.git
  - git+https://github.com/hyriver/pygeoutils.git
  - git+https://github.com/hyriver/pynhd.git
  - git+https://github.com/hyriver/py3dep.git
  - git+https://github.com/hyriver/pygeohydro.git
