blank_issues_enabled: false
contact_links:
- name: 💡 Ideas & Discussion
  url: https://github.com/hyriver/hyriver.github.io/discussions/categories/ideas
  about: Do you have an idea how to improve HyRiver? Feel free to post it to the discussion forum that allows voting for other users.
- name: ⁉️ Help & Support
  url: https://github.com/hyriver/hyriver.github.io/discussions/categories/q-a
  about: Need help with installation or usage of HyRiver? Please use the discussion forum.
